### ISSUE TITLE
DCB Table problem

### ISSUE THREAD

**Issue by IkkyPhoenix** [1Revenger1/NVCAP-Calculator#2]
Hi, i'm trying to generate a NVCAP for a 680M.
I have two bios that works on my laptop.
One gives me: "DCB Header is at 0xffff with length 0xb2
DCB Version 2.13
To old version - GPU incompatible with macOS
Invalid DCB Signature"
The other:"DCB Header is at 0xffff with length 0xe4
DCB Version 11.2
Unknown version
Invalid DCB Signature"
Is there hope for this board?
Thanks!

**Comment by 1Revenger1** [comment]
I was never able to read the DCB from 5xx series and above - it's in a difference location and needs to be treated differently. I haven't found any sources or code though on how to handle 5xx and above, so for now you are out of luck

**Comment by time-spacex** [comment]
Hi, can you tell me please, is there any solution:
palit gtx 1060 3 gb, bios link - https://www.techpowerup.com/vgabios/?architecture=&manufacturer=Palit&model=GTX+1060+3GB&version=&interface=&memType=&memSize=3072&since=
I tried both, I get the following:
Read ROM file /Users/user/Palit.GTX10603GB.3072.170818.rom, which is 258560 bytes long
DCB header is at 0x0 with length 0x56
DCB Version 4.14
Unknown version
Invalid DCB Signature
Press the enter key to continue...

**Comment by Denial-Steinberg** [comment]
I have this problem too on Asus GTX 750 Ti
https://drive.google.com/drive/folders/1RyE3bWMyuHCz7XDNEN8832ltSzql1TxC?usp=sharing

**Comment by averycblack** [comment]
As noted in the readme, only 400 series cards and older are supported. The location of the DCB table is not located in the same place so the utility is unable to find it. PRs (or more info about where the tables should be in new cards) would be appreciated. I wouldn't mind adding a fix for these cards.

**Comment by Denial-Steinberg** [comment]
![NVCAP](https://github.com/user-attachments/assets/f78d136f-e8f6-4c3d-b428-598160010337)
At the time of the snow leopard there was a table from nerone, most likely it is outdated because there is no hdmi there. Perhaps you can do something similar or do you have information?
